FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir kafka-python-ng pydantic python-dotenv psycopg2-binary

COPY ingestion /app/ingestion

ENV PYTHONPATH=/app
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV POSTGRES_HOST=postgres
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB_WAREHOUSE=warehouse
ENV POSTGRES_INGESTION_USER=ingestion_user

CMD ["python", "ingestion/tap_consumer.py", "--bootstrap-servers", "kafka:9092", "--batch-size", "250"]
