FROM apache/airflow:2.9.3

USER airflow
RUN pip install --no-cache-dir \
    dbt-core>=1.8.0 \
    dbt-postgres>=1.8.0 \
    pydantic>=2.7.0 \
    requests>=2.32.0 \
    python-dotenv>=1.0.1 \
    kafka-python-ng>=2.2.0
